# Generated by Django 3.1.7 on 2021-05-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210428_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
