image: docker/compose:alpine-1.28.0

stages:
  - build
  - test
  - deploy

before_script:
  - apk add make
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - cp $DOT_ENV $(PWD)/.env

# === BUILD ===
build.test:
  stage: build
  script: # commands to execute
    - make build
    - docker-compose push
  tags: # tags to select specific runners
    - job:build
  only: # branches to trigger
    - deployment/test
  environment: # env name to get env variables
    name: test

build.prod:
  stage: build
  script: # commands to execute
    - make build
    - docker-compose push
  tags: # tags to select specific runners
    - job:build
  only: # branches to trigger
    - deployment/prod
  environment: # env name to get env variables
    name: prod

# === TEST ===
test.test:
  stage: test
  script: # commands to execute
    - docker-compose pull
    - make test
  tags: # tags to select specific runners
    - job:test
  only: # branches to trigger
    - deployment/test
  environment: # env name to get env variables
    name: test

test.prod:
  stage: test
  script: # commands to execute
    - docker-compose pull
    - make test
  tags: # tags to select specific runners
    - job:test
  only: # branches to trigger
    - deployment/prod
  environment: # env name to get env variables
    name: prod

# === DEPLOY ===
deploy.test/1:
  stage: deploy
  script: # commands to execute
    - docker-compose pull
    - make up
  tags: # tags to select specific runners
    - job:deploy.test/1
  only: # branches to trigger
    - deployment/test
  environment: # env name to get env variables
    name: test

deploy.prod/1:
  stage: deploy
  script: # commands to execute
    - docker-compose pull
    - make down up
  tags: # tags to select specific runners
    - job:deploy.prod/1
  only: # branches to trigger
    - deployment/prod
  environment: # env name to get env variables
    name: prod
  when: manual
