version: "3.4"

volumes:
  media_volume:
    driver: sapk/plugin-rclone:v0.0.10
    driver_opts:
      config: ${RCLONE_CONFIG_BASE64}
      remote: "remote_s3:${AWS_STORAGE_BUCKET_NAME}${AWS_S3_PATH}"
