# Generated by Django 3.1.1 on 2020-09-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
    ]
